#!/bin/bash 
op=$1
ison="on"
isoff="off"

if [[ $UID != 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

if [[ $op == $ison ]]; then 
	echo  1 > /sys/devices/system/cpu/intel_pstate/no_turbo
	cpupower frequency-set --governor powersave
	echo "powersaving on, turbo disabled" 
else 
	if [[ $op == $isoff ]]; then
		echo  0 > /sys/devices/system/cpu/intel_pstate/no_turbo
		cpupower frequency-set --governor performance
		echo "powersaving off, turbo enabled" 
	else
		echo "specify on or off"
	fi
fi

